"""Initial migration

Revision ID: 951a887bb0e7
Revises: 
Create Date: 2025-06-22 05:59:14.012655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951a887bb0e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employees',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('sharedSettingsId', sa.String(), nullable=True),
    sa.Column('accountId', sa.String(), nullable=True),
    sa.Column('identifier', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('deactivated', sa.Integer(), nullable=True),
    sa.Column('invited', sa.Integer(), nullable=True),
    sa.Column('emailVerified', sa.Boolean(), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('systemPermissions', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=True),
    sa.Column('statuses', sa.JSON(), nullable=True),
    sa.Column('priorities', sa.JSON(), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=True),
    sa.Column('payroll', sa.JSON(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('creatorId', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('screenshotSettings', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_projects',
    sa.Column('employeeId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('employeeId', 'projectId')
    )
    op.create_table('project_teams',
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('teamId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('projectId', 'teamId')
    )
    op.create_table('tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('billable', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('deadline', sa.Integer(), nullable=True),
    sa.Column('labels', sa.JSON(), nullable=True),
    sa.Column('creatorId', sa.String(), nullable=False),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('createdAt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['creatorId'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shifts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('timezoneOffset', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('user', sa.String(), nullable=True),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('computer', sa.String(), nullable=True),
    sa.Column('hwid', sa.String(), nullable=True),
    sa.Column('os', sa.String(), nullable=True),
    sa.Column('osVersion', sa.String(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('payRate', sa.Float(), nullable=True),
    sa.Column('overtimePayRate', sa.Float(), nullable=True),
    sa.Column('overtimeStart', sa.Integer(), nullable=True),
    sa.Column('employeeId', sa.String(), nullable=False),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('taskId', sa.String(), nullable=True),
    sa.Column('startTranslated', sa.Integer(), nullable=True),
    sa.Column('endTranslated', sa.Integer(), nullable=True),
    sa.Column('overtimeStartTranslated', sa.Integer(), nullable=True),
    sa.Column('negativeTime', sa.Integer(), nullable=True),
    sa.Column('deletedScreenshots', sa.Integer(), nullable=True),
    sa.Column('lastActivityEnd', sa.Integer(), nullable=True),
    sa.Column('lastActivityEndTranslated', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_employees',
    sa.Column('taskId', sa.String(), nullable=False),
    sa.Column('employeeId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('taskId', 'employeeId')
    )
    op.create_table('task_teams',
    sa.Column('taskId', sa.String(), nullable=False),
    sa.Column('teamId', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('taskId', 'teamId')
    )
    op.create_table('screenshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('productivity', sa.Float(), nullable=True),
    sa.Column('employeeId', sa.String(), nullable=False),
    sa.Column('appId', sa.String(), nullable=True),
    sa.Column('appOrgId', sa.String(), nullable=True),
    sa.Column('appTeamId', sa.String(), nullable=True),
    sa.Column('teamId', sa.String(), nullable=True),
    sa.Column('organizationId', sa.String(), nullable=False),
    sa.Column('projectId', sa.String(), nullable=True),
    sa.Column('taskId', sa.String(), nullable=True),
    sa.Column('shiftId', sa.String(), nullable=True),
    sa.Column('srcEmployeeId', sa.String(), nullable=True),
    sa.Column('srcTeamId', sa.String(), nullable=True),
    sa.Column('timestamp', sa.Integer(), nullable=False),
    sa.Column('timestampTranslated', sa.String(), nullable=True),
    sa.Column('systemPermissions', sa.JSON(), nullable=True),
    sa.Column('next', sa.String(), nullable=True),
    sa.Column('imageUrl', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['employeeId'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['organizationId'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['projectId'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['shiftId'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['taskId'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['teamId'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('screenshots')
    op.drop_table('task_teams')
    op.drop_table('task_employees')
    op.drop_table('shifts')
    op.drop_table('tasks')
    op.drop_table('project_teams')
    op.drop_table('employee_projects')
    op.drop_table('projects')
    op.drop_table('employees')
    op.drop_table('teams')
    op.drop_table('organizations')
    # ### end Alembic commands ###